on:
  pull_request:
    types: [closed]

jobs:
  delete-hasura-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.1

      - name: Remove Vercel env variable for preview instance
        continue-on-error: true
        run: npx vercel --token ${{ env.VERCEL_TOKEN }} env rm REACT_APP_HASURA_URL preview ${{ steps.branch-name.outputs.current_branch }} -y
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

      - name: Hasura Cloud Preview Apps
        uses: hasura/hasura-cloud-preview-apps@v0.1.4
        with:
          name: "coordinape-${{github.env.GITHUB_HEAD_REF}}${{github.event.number}}"
          delete: true
          postgresDBConfig: |
            POSTGRES_SERVER_CONNECTION_URI=${{secrets.POSTGRES_STAGING_CONNECTION_URI}}
            PG_ENV_VARS_FOR_HASURA=HASURA_GRAPHQL_DATABASE_URL
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          HASURA_CLOUD_ACCESS_TOKEN: ${{secrets.HASURA_CLOUD_ACCESS_TOKEN}}
